[project]
name = "abbyy-bank-mcp-tools"
version = "1.0.0"
description = "ABBYY Bank MCP server - Tools Exercise"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [] 
